# Objective:-

Learn Python basics and perform basic data exploration and cleaning using Pandas. Steps:

1.Load a CSV dataset into a Pandas DataFrame.

2.Explore data (head/tail, shape, columns, data types).

3.Handle missing values (identify, fill/drop).

4.Perform basic operations (filter rows, select columns).

5.Remove duplicates.

6.Create a derived column (total_amount = price * quantity).

7.Save the cleaned dataset as a new CSV file.

Output: Jupyter Notebook (.ipynb) + cleaned CSV + brief summary.

### 1.Loading the necessary Python Libraries

In [45]:
import pandas as pd
import numpy as np

### 2.Loading the CSV dataset into Pandas DataFrame

In [5]:
ecommerce_data = pd.read_csv("e-commerce1_dataset.csv")
ecommerce_data

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

### 3.Explore data (head/tail, shape, columns, data types)

In [6]:
ecommerce_data.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

The number of visible rows can be changed by passing any desired value in place of `x` in `head(x)`. For example, `head(10)` displays the first 10 rows of the dataset.

In [7]:
ecommerce_data.head(2)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks

In [8]:
ecommerce_data.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [9]:
ecommerce_data.tail(2)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [10]:
ecommerce_data.shape

(1000, 24)

In [11]:
ecommerce_data.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [12]:
list(ecommerce_data.columns)

['product_id',
 'title',
 'product_description',
 'rating',
 'ratings_count',
 'initial_price',
 'discount',
 'final_price',
 'currency',
 'images',
 'delivery_options',
 'product_details',
 'breadcrumbs',
 'product_specifications',
 'amount_of_stars',
 'what_customers_said',
 'seller_name',
 'sizes',
 'videos',
 'seller_information',
 'variations',
 'best_offer',
 'more_offers',
 'category']

In [13]:
ecommerce_data.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

The data type of each column can be found separately using the appropriate function or attribute

In [14]:
ecommerce_data['rating'].dtypes

dtype('float64')

In [15]:
ecommerce_data['product_id'].dtypes

dtype('int64')

### 4. Handle missing values (identify, fill/drop)

In [16]:
ecommerce_data.head(3)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks

In [17]:
ecommerce_data.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [18]:
ecommerce_data[['discount','what_customers_said','videos','seller_information','variations']].sample(3)

,discount,what_customers_said,videos,seller_information,variations
393,70.0,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,NaN,NaN
349,58.0,"[{""percentage"":""52"",""value_name"":""Fit, Just Ri...",NaN,Fir███Flo███ 27█████████ Ku███████████████████...,"[{},{},{},{},{},{},{}]"
854,NaN,NaN,"[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{}]"

Instead of assigning the result back to the column using `ecommerce_data['what_customers_said'] = ecommerce_data['what_customers_said'].fillna('No reviews')`, `fillna('No reviews', inplace=True)` can also be used. With `inplace=True`, the changes are applied directly to the original dataset without needing reassignment."

In [19]:
ecommerce_data['discount'] = ecommerce_data['discount'].fillna(0)

In [20]:
ecommerce_data['what_customers_said'] = ecommerce_data['what_customers_said'].fillna('No reviews')

In [21]:
ecommerce_data['seller_name'] = ecommerce_data['seller_name'].fillna('Unknown Seller')

In [22]:
ecommerce_data['videos'] = ecommerce_data['videos'].fillna('Unknown')

In [23]:
ecommerce_data['seller_information'] = ecommerce_data['seller_information'].fillna('[]')

In [24]:
ecommerce_data['variations'] = ecommerce_data['variations'].fillna('[]')

In [25]:
ecommerce_data.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

### 5.Perform basic operations (filter rows, select columns)

In [26]:
ecommerce_data[ecommerce_data['discount']>=80]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
18,22409156,Kastner,Women Textured Tang Slim Belt,3.8,9,1399,84.0,"""₹223.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,Kas███r L███her█████████Pvt██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",Unknown,A-5███ADA███R V█████████ De█████████████████████,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",belts
21,1728397,Mactree,Men Brown Solid Mid-Top Flat Boots,3.9,1727,9060,88.0,"""₹1,087.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"{""1_star"":228,""2_stars"":89,""3_stars"":186,""4_st...",No reviews,MAX███ IN███NAT██████,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...",Unknown,"21/███10 ███NS █████████4 ,███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",boots
47,19206416,ABELINO,Women Set of 3 Assorted Cotton Boy Shorts Brie...,3.6,14,1899,80.0,"""₹379.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":2,""2_stars"":3,""3_stars"":1,""4_stars"":...",No reviews,ARI███T T███ING█████████,"[{""size"":""S"",""value"":""26.0in"",""value_name"":""To...",Unknown,F-2███RST███OOR█████████7VA███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
102,21988674,Sangria,Floral Printed Tiered A-Line Dress,0.0,0,2999,80.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,SWARR,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,D-2███Sec███ 06█████████uta███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
114,18951632,Berrylush,Women White Floral Pattern Play Dress,3.9,69,1899,80.0,"""₹379.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":13,""2_stars"":2,""3_stars"":5,""4_stars""...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""S"",""value"":""33.0in"",""value_name"":""Fr...",Unknown,Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
176,13382036,plusS,Women Olive Green Accordion Pleated Midi A-Lin...,4.2,623,1899,83.0,"""₹322.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":47,""2_stars"":31,""3_stars"":60,""4_star...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",Shi███Int███ati█████████rel███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",Unknown,Fir███and███con█████████A 3███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
213,10125241,KARATCART,Green Gold-Plated Beaded Enamelled Floral Chan...,4.2,22,1711,82.0,"""₹307.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":1,""2_stars"":3,""3_stars"":2,""4_stars"":...",No reviews,KOK███V G███AL █████████,"[{""size"":""Onesize""}]",Unknown,Sho███58-███Sec█████████ain███████████████████...,[],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
215,20064092,AMI,Set Of 25 Gold-Toned Gold Plated Contemporary ...,3.8,6,1995,80.0,"""₹399.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...",No reviews,ZAV███ PE███S,"[{""size"":""Onesize""}]",Unknown,"12,███T F███R, █████████LDG███████████████████...",[],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
227,13401002,Adwitiya Collection,Gold-Toned & Green Dome Shaped Jhumkas,0.0,0,3189,81.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,ADW███YA ███HIO█████████ LI██████,"[{""size"":""Onesize""}]",Unknown,"D-1███ Vi███ Vi█████████, U█████████████████████",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
228,13340876,Kord Store,Red Gold Plated Meenakari Classic Jhumkas,4.4,7,4524,88.0,"""₹542.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,Kor███yst███,"[{""size"":""Onesize""}]",Unknown,"1st███oor███apa█████████,Na███████████████████...",[],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
229,12930940,TOKYO TALKIES X rubans FASHION ACCESSORIES,Gold-Plated & White Contemporary Drop Earrings,3.9,14,1650,81.0,"""₹313.00""",INR,http://assets.myntassets.com/assets/images/129...,...,"{""1_star"":1,""2_stars"":3,""3_stars"":0,""4_stars"":...",No reviews,Sup███om ███,"[{""size"":""Onesize""}]",Unknown,Plo███o- ███ 1s█████████Sui███████████████████...,[],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
236,22593680,ZENEME,Gold-Plated Dome Shaped Jhumkas Earrings,0.0,0,2999,87.0,"""₹389.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,GLO███ NE███,"[{""size"":""Onesize""}]",Unknown,FIR███FLO███ 50█████████ND ███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
356,19837040,High Star,Women Olive Green Solid Crop Padded Jacket,4.1,41,3749,85.0,"""₹3,749.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown Seller,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Bu...",Unknown,[],"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets
357,19837008,High Star,Women Navy Blue Solid Parka Jacket,3.9,32,4549,85.0,"""₹4,549.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":5,""2_stars"":2,""3_stars"":2,""4_stars"":...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Unknown Seller,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Bu...",Unknown,[],"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets
447,12509548,Ishin,Women Maroon & Off-White Printed A-Line Kurta ...,0.0,0,3899,86.0,"""₹545.00""",INR,http://assets.myntassets.com/assets/images/125...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Men███Bra███Tec█████████ Pr███████████████,"[{""size"":""S"",""value"":""36.5in"",""value_name"":""Bu...",Unknown,2nd███oor███O. █████████Lan███████████████████...,[],"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",kurtas
455,19027344,Jompers,Men Maroon Ethnic Motifs Kurta with Churidar,0.0,0,3499,80.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,IND███ NE███E P█████████MIT███,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Ch...",Unknown,"HOU███NO.███ GR█████████R, ███████████████████...","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",kurta-sets
491,17359602,Swiss Design,Pack Of 20 Assorted 5-Ply Anti-Pollution N95 M...,3.0,2,1500,85.0,"""₹225.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,HOU███OF ███NDS█████████LLP███,"[{""size"":""Onesize""}]",Unknown,3RD███OOR███ AN█████████OCK███████████████████...,[],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",outdoor-masks
507,15294314,Zaveri Pearls,Set of 2 Rose Gold Plated CZ-Studded Contempor...,4.4,27,1995,82.0,"""₹359.00""",INR,http://assets.myntassets.com/assets/images/152...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":4,""4_stars"":...",No reviews,ZAV███ PE███S,"[{""size"":""Onesize""}]",Unknown,"12,███T F███R, █████████LDG███████████████████...",[],"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",ring
508,16254760,Zaveri Pearls,Set Of 3 Gold-Plated White & Green Kundan-Stud...,4.2,504,2250,81.0,"""₹2,250.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":33,""2_stars"":26,""3_stars"":57,""4_star...",No reviews,Unknown Seller,"[{""size"":""Onesize"",""value"":""2.5in"",""value_name...","[""rw-16254760_cae700"",""https://videos.myntasse...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",ring
512,15679734,John Karsun,Men Black Comfort Sandals,2.7,10,3649,81.0,"""₹693.00""",INR,http://assets.myntassets.com/assets/images/156...,...,"{""1_star"":3,""2_stars"":3,""3_stars"":1,""4_stars"":...",No reviews,KAR███ OV███EAS███,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...",Unknown,179███Kav███ Ku█████████2Ka███████████████████...,[],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sandals
540,19823504,VAIRAGEE,Black Embellished Sequinned Celebrity Saree,4.2,19,9995,83.0,"""₹1,699.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fabric Qual...",Viv███ In███nat██████,"[{""size"":""Onesize""}]",Unknown,201███ew ███dar█████████mar███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sarees
628,18690268,Dennis Lingo,Men Slim Fit Tropical Casual Shirt,4.6,5,1999,80.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",No reviews,Unknown Seller,"[{""size"":""38"",""value"":""39.0in"",""value_name"":""C...",Unknown,[],[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
681,14480064,AfroJack,Men Black Textile Long Distance Running Non-Ma...,3.1,46,3995,80.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":14,""2_stars"":3,""3_stars"":6,""4_stars""...",No reviews,WIN███INT███ATI██████,"[{""size"":""7"",""value"":""27.0cm"",""value_name"":""To...","[""rw-14480064_cae700""]","PLO███O. ███18,█████████RJE███████████████████...",[],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
767,17156676,Thomas Scott,Men Green Sustainable Sweatshirt,3.6,20,4799,85.0,"""₹4,799.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":3,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown Seller,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Ch...",Unknown,[],"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sweatshirts
769,17157846,Thomas Scott,Men Blue Sustainable Sweatshirt,3.5,10,3999,82.0,"""₹3,999.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",Unknown Seller,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Ch...",Unknown,[],"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sweatshirts
801,13466462,Global Desi,Pink Geometric Printed Slit Sleeves A-line Top,3.4,11,1599,80.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Unknown Seller,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""B...",Unknown,[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
842,18972596,MALHAAR,White & Brown Print Smocked Cinched Waist Top,0.0,0,3329,82.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",Unknown,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
874,17950198,PURVAJA,Women Solid Pink Round Neck Leg of Mutton Slee...,3.4,29,2199,81.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/179...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Loose""...",Unknown Seller,"[{""size"":""S"",""value"":""32.0in"",""value_name"":""To...",Unknown,[],"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
888,17950208,PURVAJA,Pink Solid Crop Top,3.5,20,2199,81.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/179...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Unknown Seller,"[{""size"":""S"",""value"":""32.0in"",""value_name"":""To...",Unknown,[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
896,17950338,PURVAJA,Women Peach-Coloured Crop Top,4.2,16,2199,81.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/179...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",No reviews,Unknown Seller,"[{""size"":""S"",""value"":""32.0in"",""value_name"":""To...",Unknown,[],"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
897,11876926,AND,Women Blue Printed Top,4.4,57,1999,80.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/118...,...,"{""1_star"":7,""2_stars"":0,""3_stars"":1,""4_stars"":...",No reviews,Unknown Seller,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...","[""rw-11876926_cae700""]",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
920,18688608,Nasher Miles,Jaisalmer Textured Large Trolley Bag,3.3,8,17995,85.0,"""₹17,995.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,Unknown Seller,"[{""size"":""S"",""value"":""55.0cm"",""value_name"":""Ba...",Unknown,[],"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",trolley-bag
925,22323008,Dennis Lingo,Men Slim Fit Chino Trousers,3.8,5,3099,82.0,"""₹557.00""",INR,http://assets.myntassets.com/assets/images/223...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",No reviews,Men███Bra███Tec█████████ Pr███████████████,"[{""size"":""28"",""value"":""23.0in"",""value_name"":""T...",Unknown,2nd███oor███O. █████████Lan███████████████████...,"[{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",trousers
963,20085320,BULLMER,Men Pack of 2 Navy Blue & Turquoise Blue Long ...,4.8,12,3998,80.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,Bod███ove███par█████████,"[{""size"":""M"",""value"":""39.0in"",""value_name"":""Ch...",Unknown,Bod███ove███par█████████ No███████████████████...,[],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
965,12987894,AMERICAN EAGLE OUTFITTERS,Women White & Yellow Printed Round Neck T-shirt,4.4,5,1799,80.0,"""₹359.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",No reviews,Wes███ry ███din█████████d_M██████,"[{""size"":""XS"",""value"":""29.0in"",""value_name"":""T...",Unknown,"Gro███ Fl███, N█████████old███████████████████...",[],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
976,13721540,Art Street,Set Of 3 Brown & Green Monuments Theme Framed ...,3.9,8,3500,84.0,"""₹560.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No reviews,EDG███QUA███,"[{""size"":""Onesize""}]",Unknown,I-6███URA███R I█████████ AR███████████████████...,[],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",wall-art
990,9053317,TIMESMITH,Men Black Analogue Watch TSC-008,3.7,304,2499,88.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/905...,...,"{""1_star"":54,""2_stars"":20,""3_stars"":34,""4_star...",No reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9053317_cae700"",""https://videos.myntasset...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches

In [27]:
ecommerce_data[ecommerce_data['rating']>=4.6]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,[],"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,Unknown Seller,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",Unknown,[],[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
22,21427828,London Rag,Women Stiletto Heeled High-Top Boots,5.0,4,9599,60.0,"""₹3,839.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,VOL███FAS███N P█████████,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...",Unknown,SAI███USE███OT █████████ NA███████████████████...,[],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",boots
32,18656766,VStar,Beige Solid T-Shirt Bra,4.6,5,345,0.0,"""₹345.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,V S███ CR███ION█████████,"[{""size"":""30B"",""value"":""31.5in"",""value_name"":""...",Unknown,VI/███ AB███ ST█████████ODE███████████████████...,[],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
38,21873792,KARATCART,Cubic Zirconia Silver-Plated Wraparound Bracelet,4.6,5,3397,76.0,"""₹815.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",No reviews,KOK███V G███AL █████████,"[{""size"":""Onesize"",""value"":""8.26in"",""value_nam...",Unknown,Sho███58-███Sec█████████ain███████████████████...,[],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bracelet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,20085320,BULLMER,Men Pack of 2 Navy Blue & Turquoise Blue Long ...,4.8,12,3998,80.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,Bod███ove███par█████████,"[{""size"":""M"",""value"":""39.0in"",""value_name"":""Ch...",Unknown,Bod███ove███par█████████ No███████████████████...,[],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
968,19291812,Mad Over Print,Women Black Love Wins Oversize T-shirt,4.8,5,1599,58.0,"""₹671.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MAD███R P███T P█████████MIT███,"[{""size"":""S"",""value"":""39.3in"",""value_name"":""Bu...",Unknown,621███ 6n███ kh█████████zia███████████████████...,[],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
986,17697474,Timex,Women White Dial & Gold Toned Analogue Watch T...,4.9,8,1995,20.0,"""₹1,596.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,TIM███T R███IL █████████RIV████████████,"[{""size"":""Onesize""}]",Unknown,"Fla███o. ███, 6█████████y C███████████████████...",[],"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",watches
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.0,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No reviews,Fla███ech███tai███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","3rd███165███th █████████, s███████████████████...",[],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches

In [28]:
ecommerce_data[(ecommerce_data['discount']>=80) & (ecommerce_data['rating']>=4.6)]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
628,18690268,Dennis Lingo,Men Slim Fit Tropical Casual Shirt,4.6,5,1999,80.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",No reviews,Unknown Seller,"[{""size"":""38"",""value"":""39.0in"",""value_name"":""C...",Unknown,[],[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
963,20085320,BULLMER,Men Pack of 2 Navy Blue & Turquoise Blue Long ...,4.8,12,3998,80.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,Bod███ove███par█████████,"[{""size"":""M"",""value"":""39.0in"",""value_name"":""Ch...",Unknown,Bod███ove███par█████████ No███████████████████...,[],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [29]:
ecommerce_data[['title','initial_price','final_price','discount']]

              title  initial_price   final_price  discount
0       Lino Perros           3995   "₹3,995.00"      58.0
1    Tommy Hilfiger           2899   "₹2,899.00"      35.0
2             Lavie           2999   "₹2,999.00"      65.0
3            F Gear           1675   "₹1,675.00"      52.0
4         MYTRIDENT           2899   "₹2,899.00"      17.0
..              ...            ...           ...       ...
995           KREDO          11890  "₹11,890.00"      50.0
996           GUESS           8900   "₹8,900.00"      45.0
997        GIORDANO           7950   "₹7,950.00"      50.0
998        Fastrack           3295   "₹2,636.00"      20.0
999         BOLDFIT            699     "₹699.00"      31.0

[1000 rows x 4 columns]

In [30]:
ecommerce_data[['product_id', 'title', 'category', 'rating', 'ratings_count']]

     product_id           title   category  rating  ratings_count
0       8376765     Lino Perros  backpacks     3.8             15
1       9136281  Tommy Hilfiger  backpacks     4.5             67
2      17633752           Lavie  backpacks     4.4            226
3       1376949          F Gear  backpacks     4.4           1052
4      13939916       MYTRIDENT  bath-robe     4.7             12
..          ...             ...        ...     ...            ...
995    13698258           KREDO    watches     3.5             11
996    16896006           GUESS    watches     5.0             22
997     1708108        GIORDANO    watches     2.8              5
998    19280114        Fastrack    watches     4.3             17
999    18601682         BOLDFIT  yoga-mats     3.8            161

[1000 rows x 5 columns]

In [31]:
ecommerce_data[['seller_name', 'seller_information', 'best_offer', 'more_offers']]

,seller_name,seller_information,best_offer,more_offers
0,Unknown Seller,[],{},"[{""offer_name"":""10% Instant Discount on Citi C..."
1,Unknown Seller,[],{},"[{""offer_name"":""10% Instant Discount on Citi C..."
2,Unknown Seller,[],{},"[{""offer_name"":""10% Instant Discount on Citi C..."
3,Unknown Seller,[],{},"[{""offer_name"":""10% Instant Discount on Citi C..."
4,Unknown Seller,[],{},"[{""offer_name"":""10% Instant Discount on IndusI..."
...,...,...,...,...
995,Unknown Seller,[],{},"[{""offer_name"":""10% Instant Discount on Citi C..."
996,Unknown Seller,[],{},"[{""offer_name"":""10% Instant Discount on Citi C..."
997,Unknown Seller,[],{},"[{""offer_name"":""10% Instant Discount on Citi C..."
998,Tru███m R███il,Sho███o. ███-10█████████enu███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI..."
999,Unknown Seller,[],{},"[{""offer_name"":""10% Instant Discount on Citi C..."

### 6.Find and Remove the duplicates

In [32]:
ecommerce_data.duplicated().sum()

np.int64(0)

# No duplicate data was found in this dataset. If duplicate rows are present, they can be removed using the `drop_duplicates()` function."

### 7. Create a derived column (total_amount = price * quantity)

In [33]:
ecommerce_data.sample()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
105,18962890,Athena,Fuchsia Solid Asymmetric Hem A-Line Maxi Dress,4.0,34,2499,64.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":5,""2_stars"":2,""3_stars"":2,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",APE███PPA███S,"[{""size"":""XS"",""value"":""32.5in"",""value_name"":""B...",Unknown,"Plo███o. ███, P█████████2Se███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

To calculate the total value by multiplying `final_price` and `quantity`, both columns must have numeric data types (`int` or `float`). However, `final_price` is stored as a string, as shown in `ecommerce_data.dtypes`. Therefore, the string values are first cleaned using the `replace()` function and then converted to a numeric type using `astype()`. After the conversion, operations such as multiplication can be performed easily.

In [34]:
ecommerce_data['final_price'] = ecommerce_data['final_price'].str.replace(r'[₹,"]','',regex=True).astype(float).astype(int)

In [40]:
ecommerce_data.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                 int64
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
total_amount                int64
dtype: object

In [41]:
ecommerce_data['total_amount'] = ecommerce_data['final_price'] * ecommerce_data['ratings_count']

In [42]:
ecommerce_data.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995,INR,http://assets.myntassets.com/assets/images/837...,...,No reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",[],[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,59925
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899,INR,http://assets.myntassets.com/assets/images/913...,...,No reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",[],"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,194233
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999,INR,http://assets.myntassets.com/assets/images/176...,...,No reviews,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",[],"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,677774
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675,INR,http://assets.myntassets.com/assets/images/137...,...,No reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1762100
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899,INR,http://assets.myntassets.com/assets/images/pro...,...,No reviews,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,[],"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,34788

In [43]:
ecommerce_data.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995,INR,http://assets.myntassets.com/assets/images/837...,...,No reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",[],[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,59925
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899,INR,http://assets.myntassets.com/assets/images/913...,...,No reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",[],"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,194233
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999,INR,http://assets.myntassets.com/assets/images/176...,...,No reviews,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",[],"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,677774
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675,INR,http://assets.myntassets.com/assets/images/137...,...,No reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1762100
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899,INR,http://assets.myntassets.com/assets/images/pro...,...,No reviews,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,[],"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,34788

### 8.Saving the cleaned dataset as a new CSV file.

In [44]:
ecommerce_data.to_csv('cleaned_ecommerce_data.csv', index=False)